matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.lint
    - stage: "Build /w Webpack"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode10.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm run ci.build && npm pack
        - cd ../demo && tns plugin add ../src/*.tgz
        - npm i && tns build ios --bundle --env.aot --env.uglify
        - cd ../demo-ng && tns plugin add ../src/*.tgz
        - npm i && tns build ios --bundle --env.aot --env.uglify
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd src && npm run ci.build && npm pack
        - cd ../demo && tns plugin add ../src/*.tgz
        - tns build ios --bundle --env.aot --env.uglify
        - cd ../demo-ng && tns plugin add ../src/*.tgz
        - tns build android --bundle --env.aot --env.uglify
    # TODO: E2E tests
    # - os: linux
    #   language: android
    #   dist: precise
    #   sudo: required
    #   jdk: oraclejdk8
    #   before_script:
    #     - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
    #     - emulator -avd test -no-audio -no-window &
    #     - android-wait-for-emulator
    #   before_install:
    #     - nvm install 6
    #   script: cd src && npm run test.android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    # - android-21
    - android-28
    - extra-android-m2repository
    # - sys-img-armeabi-v7a-android-21

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable